---
- name: common installations
  hosts: all
  become: yes
  become_user: root
  vars_files:
  - env_variables 


  tasks:
    - name: Create a repository file for kubernetes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch

    - name: Adding details into kubernetes repo file
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg


    - name: installed docker, kubeadm and kubectl
      yum:
        name: "{{ packages }}"
        state: present

    - name: service started and enabled for docker, kubeadm and kubectl
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"

    - name: stop firewalld  
      tags: testing
      service:
        name: firewalld
        state: stopped

    - name: Enabling Bridge fireall rule
      shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

      #    - name: Pulling images required for setting up a Kubernetes cluster
      # shell: kubeadm config images pull

