- name: Configure kubernetes master 
  hosts: master
  become: yes
  vars_files:
    - env_variables
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Initializing kubernetes cluster(kubeadm init)
    shell: kubeadm init --apiserver-advertise-address {{ api_ad_address }} --pod-network-cidr= {{ pod_nw_cidr }} --ignore-preflight-errors=NumCPU >> cluser_initialized.txt
    args: 
      chdir: $HOME
      creates: cluser_initialized.txt

  - name: create .kube directory
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: ec2-user

  - name: Install POD network
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
    args:
      chdir: $HOME
      creates: pod_network_setup.txt
